site_name: '朱易辰的个人网站'
theme: 'readthedocs'
docs_dir: '../atskyline.docs'
site_dir: '../atskyline.github.io'

site_url: 'http://www.atskyline.com'
repo_url: 'https://github.com/atskyline/atskyline.docs'
repo_name: 'GitHub'
edit_uri: 'edit/master/'

nav:
    - 'AboutMe': 'index.md'
    - 'nginx源码注解' :
        - '源码文件分析' : 'nginx源码注解/源码文件分析.md'
        - 'reopen机制' : 'nginx源码注解/reopen机制.md'
        - 'filter机制' : 'nginx源码注解/filter机制.md'
        - '模块管理' : 'nginx源码注解/模块管理.md'
        - 'server的查找' : 'nginx源码注解/server的查找.md'
        - 'location的查找' : 'nginx源码注解/location的查找.md'